version: "3.8"

services:
  mongo:
    image: mongo:7.0.0
    container_name: request-mongodb
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - resolver-network
    restart: always
  rabbitmq:
    image: rabbitmq
    container_name: request-rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    networks:
      - resolver-network
    restart: always
networks:
  resolver-network:
        driver: bridge