version: "3.8"

services:
  service:
    container_name: resolver-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    expose:
      - "${SERVER_PORT}"
    networks:
      - cardanoservice_cardanonetwork
    extra_hosts:
      - "mongodb-host:172.17.0.1"
    volumes:
      - "./logs:/usr/src/app/logs"
networks:
  cardanoservice_cardanonetwork:
    external: true