version: "3.8"

services:
  service:
    image: resolver-service
    container_name: resolver-service
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    expose:
      - "${SERVER_PORT}"
    networks:
      - cardanonetwork
    extra_hosts:
      - "mongohost:172.17.0.1"

  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   volumes:
  #     - ./docker-data/mongo:/data/db
  #   ports:
  #     - "${MONGO_PORT}:${MONGO_PORT}"
  #   expose:
  #     - "${MONGO_PORT}"
  #   networks:
  #     - cardanonetwork

networks:
  cardanonetwork:
    external:
      name: cardanoservice_cardanonetwork