version: "3.8"

services:
  mongo:
    image: mongo:7.0.0
    container_name: request-mongodb
    volumes:
       - ./docker-data/mongodb:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    expose:
      - "${MONGO_PORT}"
    networks:
      - resolver-network
    restart: always
  service:
    image: resolver-service
    container_name: resolver-service
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mongo
    networks:
      - resolver-network
networks:
  resolver-network:
        driver: bridge