version: "3.8"

services:
  service:
    image: resolver-service:latest
    container_name: resolver-service
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    expose:
      - "${SERVER_PORT}"
    networks:
      - cardanoservice_cardanonetwork
    extra_hosts:
      - "mongodb-host:172.17.0.1"

networks:
  cardanoservice_cardanonetwork:
    external: true